os: linux
language: rust

git:
  depth: 1

if: tag IS blank
script: make $SUITE

matrix:
  include:
    - env: SUITE=style
    - env: SUITE=lint
    - env: SUITE=test
    - env: SUITE=test
      rust: "1.31.0"

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/1adffa0c-49f3-11e8-b130-0a580a280805/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
